name: create-cluster.yml
on: [push]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - name: Install Metallb
        run: kubectl apply -f tests/metallb-native.yaml

