name: create-cluster.yml
on: [push]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - name: Install Metallb
        run: kubectl apply -f tests/metallb-native.yaml
      - name: Wait on Metallb
        run: kubectl wait -n metallb-system -l app=metallb --for condition=Ready pod
      - name: Configure Metallb
        run: kubectl apply -f tests/metallb-config.yaml


