name: create-cluster.yml
on: [push]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
      - name: Install Metallb
        run: kubectl apply -f tests/metallb-native.yaml
      - name: Wait on Metallb
        run: kubectl wait -n metallb-system -l app=metallb --for condition=Ready pod
      - name: Configure Metallb
        run: kubectl apply -f tests/metallb-config.yaml
      - name: Download tctl
        run: ./get_tctl.sh
      - name: Configure tctl
        run: tctl config clusters set default --bridge-address ${{ secrets.TSB_ADDRESS }}
      - run: tctl config users set default --username admin --password ${{ secrets.TSB_ADMIN_PASSWORD }} --org apidemo
      - run: tctl version



